* yasnippet-latex-mode

A collection of LaTeX mode snippets for [[http://capitaomorte.github.com/yasnippet/][YASnippet]]. The collection contains snippets for general writing, snippets for inserting biblatex macros that pull their key from a bibliography via RefTeX, snippets for inserting cross-references via RefTeX and snippets for inserting some logic symbols.

** Installation

Note that
- the directory the snippets are installed into needs to be named "latex-mode", and
- YASnippet needs to [[http://capitaomorte.github.com/yasnippet/snippet-organization.html#loading-snippets][know the path to the directory]].

The following describes two ways to install. The first method requires the user to have =git= installed, the second does not.

*** Git

=cd= to the directory you want to install in and do
#+BEGIN_EXAMPLE
clone https://github.com/Sleft/yasnippet-latex-mode.git .
#+END_EXAMPLE
to clone the git repository into that directory.

*** Archive

 [[https://github.com/Sleft/yasnippet-latex-mode/downloads][Download]] an archive and extract to the directory you want to install in.
